name: build

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-20.04
    container: docker.io/crowphp/php:8.0-cli-buster
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: composer install --dev
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract crowphp absolute path
        run: CROWPHP_PATH=$(pwd)
      - name: Run PHPUnit
        run: php -dxdebug.mode=coverage vendor/bin/phpunit --coverage-text --coverage-clover coverage/clover.xml --configuration=./phpunit.xml
      - name: Clone badger repository
        run: |
          cd /home
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          chmod -R 0600 ~/.ssh
          ssh-keygen -R github.com
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git clone git@github.com:crowphp/badger.git;
      - name: Setup badger secrets
        run: |
          mkdir ~/.ssh/
          eval "$(ssh-agent -s)";
          bash ./decrypt.sh;
          mv ./secrets/id_badger ~/.ssh/id_badger;
          mv ./secrets/id_badger.pub ~/.ssh/id_badger.pub;
          chmod -R 0600 ~/.ssh/;
          ssh-add ~/.ssh/id_badger;
        env:
          BADGER_ENCRYPTION_KEY: ${{ secrets.BADGER_ENCRYPTION_KEY }}
      - name: Generate coverage badge
        run: composer install && php index.php $CROWPHP_PATH ${{ steps.extract_branch.outputs.branch }}


